create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  location text not null,
  client text not null,
  scope text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.project_images (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  image_url text not null,
  storage_path text not null,
  alt_text text,
  is_cover boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists projects_location_idx on public.projects (location);
create index if not exists projects_client_idx on public.projects (client);
create index if not exists project_images_project_id_idx on public.project_images (project_id);
create index if not exists project_images_cover_idx on public.project_images (project_id, is_cover);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at
before update on public.projects
for each row
execute function public.set_updated_at();

alter table public.projects enable row level security;
alter table public.project_images enable row level security;

drop policy if exists "Public projects are readable" on public.projects;
create policy "Public projects are readable"
on public.projects
for select
to anon
using (true);

drop policy if exists "Public project images are readable" on public.project_images;
create policy "Public project images are readable"
on public.project_images
for select
to anon
using (true);

-- Create a public Supabase Storage bucket named project-images from the dashboard:
-- Storage > New bucket > Name: project-images > Public bucket: enabled
-- The backend uses SUPABASE_SERVICE_ROLE_KEY for insert/update/delete actions.
